---
title: "Information Systems"
subtitle: "Anno accademico 2022-2023"
author: [Marco  Lampis]
keywords: [Markdown]
book: true
date: "\\today"

# PDF: copertina
titlepage: true
titlepage-color: "154C79"
titlepage-text-color: "FFFFFF"
titlepage-background: "./assets/background.pdf"
titlepage-rule-height: 0

# table of contents
toc-own-page: true

# numerazione primo capitolo
first-chapter: 0
